version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-3.6-mpich
      - test-3.6-openmpi

jobs:

  test-3.6-mpich:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "asaptools-dev"
      MPI: "mpich"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-mpich-{{ checksum "ci/env-3.6-mpich.yml" }}
      - run:
          name: Install and activate conda environment
          command: ci/install.sh
      - run:
          name: Running tests
          command: ci/test_with_coverage.sh
      - run:
          name: Coverage
          command: |
            apt-get --yes install curl
            source activate ${ENV_NAME}
            curl -s https://codecov.io/bash > .codecov
            chmod +x .codecov
            ./.codecov
          when: on_success
      - save_cache:
          key: deps-{{ .Branch }}-3.6-mpich-{{ checksum "ci/env-3.6-mpich.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

  test-3.6-openmpi:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "asaptools-dev"
      MPI: "openmpi"
      OMPI_MCA_rmaps_base_oversubscribe: "1"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-openmpi-{{ checksum "ci/env-3.6-openmpi.yml" }}
      - run:
          name: Install and activate conda environment
          command: ci/install.sh
      - run:
          name: Running tests
          command: ci/test.sh
      - run:
          name: Coverage
          command: |
            apt-get --yes install curl
            source activate ${ENV_NAME}
            curl -s https://codecov.io/bash > .codecov
            chmod +x .codecov
            ./.codecov
          when: on_success
      - save_cache:
          key: deps-{{ .Branch }}-3.6-openmpi-{{ checksum "ci/env-3.6-openmpi.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"
