version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-3.6-mpich
      - test-3.6-openmpi

default-job:

jobs:

  test-3.6-mpich:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      ENV: "3.6-mpich"
      COV: "enabled"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install conda environment
          command: ci/install.sh
      - run:
          name: Run tests
          command: ci/runtests.sh
      - save_cache:
          key: deps-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/opt/conda/envs/asaptools-${PYTHON}-${MPI}/"
            - "/opt/conda/pkgs"

  test-3.6-openmpi:
    docker:
      - image: continuumio/miniconda:latest

    environment:
      ENV: "3.6-openmpi"
      OMPI_MCA_rmaps_base_oversubscribe: "1"
      OMPI_ALLOW_RUN_AS_ROOT: "1"
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"

    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install and activate conda environment
          command: ci/install.sh
      - run:
          name: Running tests
          command: ci/runtests.sh
      - save_cache:
          key: deps-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - "/opt/conda/envs/asaptools-${PYTHON}-${MPI}/"
            - "/opt/conda/pkgs"
