version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-2.7:
          filters:
            branches:
              only:
                - devel
 
jobs:

  test-2.7:
    docker:
      - image: frolvlad/alpine-miniconda3
    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n asaptools-dev python=2.7 && conda env update -f environment-dev.yml --prune
      - run: source activate asaptools-dev && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
           name: Running tests
           command: |
             source activate asaptools-dev
             python -m unittest tests.vprinterTests
