version: 2

workflows:
  version: 2
  default:
    jobs:
      - test-2.7:
          filters:
            branches:
              only:
                - devel
 
jobs:
  test-2.7:
    docker:
      - image: frolvlad/alpine-miniconda3
    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh bash curl
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda create -q -n asaptools-dev python=2.7 && conda env update -f environment-dev.yml --prune
      - run: source activate asaptools-dev && pip install --no-deps -e .
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run:
          name: Running tests
          command: |
            source activate asaptools-dev
            coverage run -p -m tests.vprinterTests
            coverage run -p -m tests.timekeeperTests
            coverage run -p -m tests.partitionTests
            coverage run -p -m tests.partitionArrayTests
            coverage run -p -m tests.simpleCommP1STests
            mpirun -np 4 coverage run -p -m tests.simpleCommParTests
            mpirun -np 4 coverage run -p -m tests.simpleCommParDivTests
            coverage combine
      - run:
          name: Coverage
          command: |
            source activate asaptools-dev
            curl -s https://codecov.io/bash > .codecov
            chmod +x .codecov
            ./.codecov
          when: on_success

